### ISSUE TITLE
chp_mask.nii.gz file error

### ISSUE THREAD

**Issue by Luoyu-Wang** [Center-of-Imaging-Biomarker-Development/chp_seg#3]
Hi! We have used version 1.0.1 of the Docker to process T1 images and have generated a chp_mask.nii.gz file. However, we are unable to open or view this file with tools like MRICron, SPM, etc. This issue did not occur with version 1.0.0, where everything worked fine.

Could you please provide guidance or a solution for this problem?

**Comment by CenterImagingBiomarkerDevelopment** [comment]
Hello Luoyu-Wang,

You should be able to load the segmentation map on any MRI visualization software. I tested it using ItkSNAP, FSLeyes, MRICron, and Slicer.

However, with the new update of the software, the first step involving rigid registration had sub-optimal parameters leading to the misalignment of the image. This could explain why you had an empty segmentation mask. 

Can you try to re-download the docker? docker pull kilianhett/chp_seg:1.0.1 
and try it again. 

Please let me know if it solves your problem.

Best,
Kilian

**Comment by Luoyu-Wang** [comment]
[n4oS0001.nii.gz](https://github.com/user-attachments/files/16323395/n4oS0001.nii.gz)
[n4oS0001_chp_mask.nii.gz](https://github.com/user-attachments/files/16323425/n4oS0001_chp_mask.nii.gz)
Here is my data, but it appears that the errors still persist.

**Comment by Luoyu-Wang** [comment]
Thank you very much for your help; the issue has been resolved. By the way, in the table, do 0 and 1 correspond to left and right, respectively?

**Comment by Luoyu-Wang** [comment]
Hi, Here is my data and segmentation. We update the images but it appears that the errors still persist.

[n4oS0001.nii.gz](https://github.com/user-attachments/files/16323532/n4oS0001.nii.gz)
[n4oS0001_chp_mask.nii.gz](https://github.com/user-attachments/files/16323533/n4oS0001_chp_mask.nii.gz)

**Comment by CenterImagingBiomarkerDevelopment** [comment]
Thank you for sharing your files with me. 

I was able to open them using itksnap (see screenshot). Are you loading the T1-weighted scan first, then the segmentation as either an additional image or as a segmentation? 

<img width="971" alt="Screenshot 2024-07-22 at 8 56 01 AM" src="https://github.com/user-attachments/assets/2c6b9161-1655-4bdd-9684-15113913e12a">

**Comment by Luoyu-Wang** [comment]
Thank you for your help, and the problem has been solved.
