### ISSUE TITLE
Choroid plexus volume

### ISSUE THREAD

**Issue by marivas-MRI** [Center-of-Imaging-Biomarker-Development/chp_seg#4]
Dear Killian, 

First of all, congratulations on this software. I would like to know if there is any way to save the volume of the choroid plexus in a text file or something similar?

Thank you very much in advance.

Best,

**Comment by hettk** [comment]
Hello Marivas,

The new version (i.e., 1..0.1) has that function. It will create a CSV file containing the volumetric for left, right, and total chp volume.

You can run the new version using the following command.

`sudo docker run -v /absolute_path_to_folder/:/data/in  -v /absolute_path_to_folder/:/data/out kilianhett/chp_seg:1.0.1 --sequence_type T1`


Please let me know if this is helpful.

Kind regards,
Kilian
